version: '2'
services:
    novi-app:
        image: novi
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://novi-mysql:3306/novi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=novi-elasticsearch:9300
        ports:
            - 8080:8080
    novi-mysql:
        extends:
            file: mysql.yml
            service: novi-mysql
    novi-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: novi-elasticsearch
